In [1]:
import numpy as np

In [2]:
mylist = [1, 2, 3]

In [3]:
type(mylist)

list

Transforming Lists Into Numpy Arrays:

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
mylist

[1, 2, 3]

In [6]:
myarr = np.array(mylist)

In [7]:
type(myarr)

numpy.ndarray

In [8]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Numpy Functions And Methods:

In [12]:
np.arange(0, 10) #Numpy's equivalent of the range() function

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [14]:
np.arange(0, 101, 20)

array([  0,  20,  40,  60,  80, 100])

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((2, 5)) #Zeroes function argument is a tuple, with rows first, then columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.linspace(0, 10, 3) #Returns evenly spaced numbers over a specified interval, but end is included.

array([ 0.,  5., 10.])

In [22]:
np.linspace(0, 10, 11) #Start, stop, # of numbers

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [23]:
np.linspace(0, 5, 21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [24]:
len(np.linspace(0, 5, 21))

21

In [26]:
np.eye(5) #Makes an identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Random Distribution Functions:

In [30]:
np.random.rand(1) #Random values in a given shape with a uniform distribution (all numbers are equally as likely to be picked)

array([0.31059756])

In [31]:
np.random.rand(5, 6)

array([[0.42352628, 0.00442125, 0.65223082, 0.6657138 , 0.0200782 ,
        0.8654314 ],
       [0.69417848, 0.01342183, 0.0592739 , 0.92241716, 0.32115534,
        0.04644335],
       [0.3719363 , 0.26826792, 0.64803249, 0.1011611 , 0.04088098,
        0.41973599],
       [0.54023828, 0.52405697, 0.74551661, 0.36832278, 0.14895475,
        0.83159267],
       [0.05137568, 0.21933313, 0.7862729 , 0.39219024, 0.25916608,
        0.83970371]])

In [32]:
np.random.rand(5, 2)

array([[0.01280765, 0.92153886],
       [0.59918927, 0.16554328],
       [0.5562149 , 0.9831625 ],
       [0.04029223, 0.56220735],
       [0.48520854, 0.29919456]])

In [33]:
np.random.randn(10) #Same as above, sut with normal distribution (mean = 0 and variance = 1, where numbers closer to 0 are more likely)

array([-0.0494572 ,  0.89601622,  0.37471815,  1.43675697,  0.00298934,
        0.74266784,  0.01136979,  2.1746928 , -0.92790475,  1.25317193])

In [34]:
np.random.randn(2, 3)

array([[-0.17080539, -0.23541846, -1.50573378],
       [ 0.90119983,  0.7990064 ,  0.21667296]])

In [36]:
np.random.randint(0, 101) #Uniform distribution, but only integers. Again, start inclusive, end exclusive

79

In [37]:
np.random.randint(0, 101, 5)

array([67, 72, 61, 83, 67], dtype=int32)

In [38]:
np.random.randint(0, 101, (4, 5))

array([[26, 74, 74,  2, 63],
       [17, 73, 56, 13, 28],
       [71, 96, 46, 71,  9],
       [50, 36, 50, 29, 51]], dtype=int32)

In [42]:
np.random.seed(42) #Useful for reproducing the same random results on multiple experiments
np.random.rand(4) #Must be done in the same cell as the seed setting
#Unlike the random module, setting the seed only lasts for one cell

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [44]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [45]:
np.random.rand(4)

array([0.68527698, 0.83389686, 0.30696622, 0.89361308])

Useful Attributes And Method Calls From Existing Numpy Arrays:

In [46]:
arr = np.arange(0, 25)

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [48]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
arr.reshape(5, 4)

ValueError: cannot reshape array of size 25 into shape (5,4)

In [50]:
ranarr = np.random.randint(0, 101, 10)

In [52]:
ranarr

array([60, 92, 64,  5, 12, 93, 40, 49, 83,  8], dtype=int32)

In [53]:
ranarr.max()

np.int32(93)

In [60]:
print(ranarr.max())

93


In [54]:
ranarr.min()

np.int32(5)

In [55]:
ranarr.argmax() #Finds the index of the max

np.int64(5)

In [56]:
ranarr.argmin() #Finds the index of the min

np.int64(3)

In [57]:
ranarr.dtype

dtype('int32')

In [61]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [62]:
arr.shape

(25,)

In [63]:
arr = arr.reshape(5, 5)

In [64]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [65]:
arr.shape

(5, 5)

In [66]:
arr.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [67]:
arr.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])